// `sudo hostler init` — one-time privileged setup that enables passwordless
// daily use: create the user config dir, add the nginx include, and install a
// minimal sudoers rule.
import { chownSync } from "node:fs";
import { mkdir, writeFile, rm } from "node:fs/promises";
import { dirname } from "node:path";
import { getRealUser, getUserConfigDir, writeInitMarker } from "../lib/config.ts";
import { run, selfPath } from "../lib/exec.ts";
import * as nginx from "../lib/nginx.ts";
import { printError, printInfo, printOk, printWarn, rule } from "../lib/ui.ts";

const SUDOERS_PATH = "/etc/sudoers.d/hostler";

export async function init(): Promise<void> {
  if (!(process.getuid && process.getuid() === 0)) {
    printError("This command requires root privileges. Please run with sudo.");
    process.exit(1);
  }

  const realUser = getRealUser();
  if (!realUser) {
    printError("Could not determine user. Make sure to run with sudo, not as root directly.");
    process.exit(1);
  }

  console.log();
  console.log("hostler init");
  console.log(rule());

  // Step 1: detect nginx.
  printInfo("Detecting nginx...");
  let cfg: nginx.NginxConfig;
  try {
    cfg = await nginx.detect();
  } catch (err) {
    printError(err instanceof Error ? err.message : String(err));
    process.exit(1);
  }
  console.log(`  nginx version: ${cfg.version}`);
  console.log(`  nginx config: ${cfg.mainConfigPath}`);

  // Step 2: create the user config directory, owned by the real user.
  console.log();
  printInfo("Creating user configuration directory...");
  const userConfigDir = getUserConfigDir(realUser.home);
  try {
    await createUserConfigDir(userConfigDir, realUser.uid, realUser.gid);
  } catch (err) {
    printError(err instanceof Error ? err.message : String(err));
    process.exit(1);
  }
  printOk(`  Created: ${userConfigDir}`);

  // Step 3: add the include directive to nginx.conf.
  console.log();
  printInfo("Adding include directive to nginx.conf...");
  let includeAdded = false;
  try {
    includeAdded = await nginx.addIncludeDirective(cfg.mainConfigPath, userConfigDir);
  } catch (err) {
    printError(err instanceof Error ? err.message : String(err));
    process.exit(1);
  }
  if (includeAdded) printOk(`  Added: include ${userConfigDir}/*.conf;`);
  else printWarn("  Include directive already exists");

  // Step 4: validate nginx config, rolling back the include on failure.
  console.log();
  printInfo("Testing nginx configuration...");
  try {
    await nginx.testConfig();
  } catch (err) {
    printError(err instanceof Error ? err.message : String(err));
    printWarn("  Rolling back changes...");
    await nginx.removeIncludeDirective(cfg.mainConfigPath, userConfigDir);
    process.exit(1);
  }
  printOk("  nginx config is valid");

  // Step 5: install the sudoers rule.
  console.log();
  printInfo("Setting up passwordless sudo...");
  try {
    await createSudoersFile(realUser.name);
  } catch (err) {
    printError(err instanceof Error ? err.message : String(err));
    printWarn("  Rolling back changes...");
    await nginx.removeIncludeDirective(cfg.mainConfigPath, userConfigDir);
    process.exit(1);
  }
  printOk(`  Created: ${SUDOERS_PATH}`);

  // Step 6: mark initialization complete (owned by the real user).
  try {
    await writeInitMarker(userConfigDir);
    chownSync(`${userConfigDir}/.initialized`, realUser.uid, realUser.gid);
  } catch (err) {
    printWarn(`Warning: Could not write init marker: ${err instanceof Error ? err.message : err}`);
  }

  console.log();
  printOk("Successfully initialized hostler!");
  console.log("\nYou can now use these commands without sudo:");
  console.log("  hostler add myapp.loc 3000");
  console.log("  hostler remove myapp.loc");
  console.log("  hostler list\n");
}

async function createUserConfigDir(configDir: string, uid: number, gid: number): Promise<void> {
  const parent = dirname(configDir);
  await mkdir(configDir, { recursive: true });
  if (uid >= 0 && gid >= 0) {
    chownSync(parent, uid, gid);
    chownSync(configDir, uid, gid);
  }
}

async function createSudoersFile(username: string): Promise<void> {
  const hostlerPath = selfPath();
  const nginxPath = await nginx.resolveNginxBin();

  const content = `# Sudoers rules for hostler CLI
# Generated by: sudo hostler init
# User: ${username}

# Allow hostler internal hosts commands
${username} ALL=(root) NOPASSWD: ${hostlerPath} _hosts-add *
${username} ALL=(root) NOPASSWD: ${hostlerPath} _hosts-remove *

# Allow nginx test and reload
${username} ALL=(root) NOPASSWD: ${nginxPath} -t
${username} ALL=(root) NOPASSWD: ${nginxPath} -s reload
`;

  // sudoers files must be mode 0440.
  await writeFile(SUDOERS_PATH, content, { mode: 0o440 });

  // Validate syntax; remove the file if visudo rejects it.
  const check = await run(["visudo", "-c", "-f", SUDOERS_PATH]);
  if (!check.ok) {
    await rm(SUDOERS_PATH, { force: true });
    throw new Error(`invalid sudoers syntax: ${check.combined}`);
  }
}
